# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Brajesh
tagline:             ''
description:         ''
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Brajesh Kumar
  url:               
  email:             

# Custom vars
version:             1.0.0
