# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Brajesh
tagline:             ''
description:         ''
url:                 https://bkumar12888.github.io
baseurl:             'https://bkumar12888.github.io'
paginate:            5

# About/contact
author:
  name:              Brajesh Kumar
  url:               
  email:             

# Custom vars
version:             1.0.0
